name: setmore_client
version: 0.0.1
description: An API client for the Setmore booking system using OpenAPI API client specification. View, Schedule, Book and Manage appointments directly from the API.
homepage: https://pub.dev/packages/setmore_client

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: '^5.2.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0
